### ISSUE TITLE
What resources does the Gravitate Health IG style sheet support?

### ISSUE THREAD

**Issue by cander2** [hl7-eu/gravitate-health#12]
Does the style sheet template in this IG support Clinical Use Definition? How can I tell which resources it supports?

I made an ePI with a bunch of interactions but they are not appearing.
[HL7.EU.FHIR.GH\ePI document Bundle for Talzenna® (talazoparib) 0.25 mg and 1mg hard capsules - FHIR v5.0.0](https://build.fhir.org/ig/hl7-eu/gravitate-health/Bundle-bundlepackageleaflet-talzenna1-025.html)

**Comment by joofio** [comment]
the changes for CUD were made on emedicinal repo. copied to this one. We can discuss what informations should we include or not on this and emedicinal as well. The information existent at the moment were the ones i felt ok to include.

**Comment by cander2** [comment]
Nice! Looks good.

Here’s the one with all the interactions. I’ll do the other CUD elements soon.
HL7.EU.FHIR.GH\ePI document Bundle for Talzenna® (talazoparib) 0.25 mg and 1mg hard capsules - FHIR v5.0.0<https://build.fhir.org/ig/hl7-eu/gravitate-health/Bundle-bundlepackageleaflet-talzenna1-025.html>

Regards,
Craig

From: João Almeida ***@***.***>
Sent: Thursday, July 13, 2023 5:06 AM
To: hl7-eu/gravitate-health ***@***.***>
Cc: Anderson, Craig ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [hl7-eu/gravitate-health] What resources does the Gravitate Health IG style sheet support? (Issue #12)


the changes for CUD were made on emedicinal repo. copied to this one. We can discuss what informations should we include or not on this and emedicinal as well. The information existent at the moment were the ones i felt ok to include.

**Comment by cander2** [comment]
We might have talked about this before but I notice the IG is add all this extra styling to the XML and JSON. Is there any way to stop this? 

Worried someone new will download samples from the IG and think this is part of the standard.

``` <text>
          <status value="generated"/>
          <div xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><p><b>Generated Narrative: Composition</b><a name="fe63fd6a-afe8-4b61-a203-0cf4a69ffb60"> </a></p><div style="display: inline-block; background-color: #d9e0e7; padding: 6px; margin: 4px; border: 1px solid #8da1b4; border-radius: 5px; line-height: 60%"><p style="margin-bottom: 0px">Resource Composition &quot;fe63fd6a-afe8-4b61-a203-0cf4a69ffb60&quot;  (Language &quot;en&quot;) </p><p style="margin-bottom: 0px">Profile: <a href="StructureDefinition-Composition-uv-epi.html">Composition (ePI)</a></p></div><p><b>identifier</b>: id: 0d69fdcb-33cf-407f-8209-a6529856ab4f</p><p><b>status</b>: final</p><p><b>type</b>: Package Leaflet <span style="background: LightGoldenRodYellow; margin: 4px; border: 1px solid khaki"> (example.org#100000155538)</span></p><p><b>date</b>: 2022-02-16 13:28:17+0000</p><p><b>author</b>: <a href="#Organization_d71bf884-90eb-47f9-81b7-fa81ecec7e75">See above (Organization/d71bf884-90eb-47f9-81b7-fa81ecec7e75)</a></p><p><b>title</b>: Example of Type 3 ePI - DrugX (acetaminophen) 75 mg tablets</p></div>
        </[text](http://hl7.org/fhir/R5/composition.html#Composition.text)>```

**Comment by jkiddo** [comment]
@cander2 are you referring to the graphical elements of https://build.fhir.org/ig/hl7-eu/gravitate-health/Bundle-bundlepackageleaflet-talzenna1-025.html#product-information ?

**Comment by cander2** [comment]
Yes, those graphical elements are great and want to keep them. 

Wondering if there is a way of achieving the same result without adding all that to the XLM/JSON files of the ePI.

**Comment by joofio** [comment]
I think @cander2  is refering to the narrative part that is generated, right?
this part
![image](https://github.com/hl7-eu/gravitate-health/assets/14195408/a57217fb-29a7-42fe-ba9c-ed04706f9073)

from here: 
http://build.fhir.org/ig/hl7-eu/gravitate-health/Bundle-bundlepackageleaflet-9e0b95f2943e17e9a39046404c6cce71.json.html

**Comment by jkiddo** [comment]
If the status is 'generated' that should be a signal to the reader.

**Comment by cander2** [comment]
Joao is correct. I did not add that content. If we were submitting that ePI to EMA (or any other health authority) it wouldn't be there.

Another example, the Ingredient resource should just have info about the ingredient but it's adding in content into the <div/>. Is this what the FHIR specification means by embedding the CSS in the document?

```
<[entry](http://hl7.org/fhir/R5/bundle.html#Bundle.entry)>
    <[fullUrl](http://hl7.org/fhir/R5/bundle.html#Bundle.entry.fullUrl) [value](http://hl7.org/fhir/R5/datatypes.html#uri)="Ingredient/ingredientMICROCRYSTALLINECELLULOSE"/>
    <[resource](http://hl7.org/fhir/R5/ingredient.html#Ingredient)>
      <[Ingredient](http://hl7.org/fhir/R5/ingredient.html#Ingredient)>
        <[id](http://hl7.org/fhir/R5/ingredient.html#Ingredient.id) [value](http://hl7.org/fhir/R5/datatypes.html#id)="ingredientMICROCRYSTALLINECELLULOSE"/>
        <[meta](http://hl7.org/fhir/R5/ingredient.html#Ingredient.meta)>
          <[profile](http://hl7.org/fhir/R5/resource.html#Meta#Meta.profile)
                   [value](http://hl7.org/fhir/R5/datatypes.html#canonical)="http://hl7.org/fhir/uv/emedicinal-product-info/StructureDefinition/Ingredient-uv-epi"/>
        </meta>
        <[text](http://hl7.org/fhir/R5/ingredient.html#Ingredient.text)>
          <[status](http://hl7.org/fhir/R5/narrative.html#Narrative#Narrative.status) [value](http://hl7.org/fhir/R5/datatypes.html#code)="generated"/>
          <div xmlns="http://www.w3.org/1999/xhtml"><p><b>Generated Narrative: Ingredient</b><a name="ingredientMICROCRYSTALLINECELLULOSE"> </a></p><div style="display: inline-block; background-color: #d9e0e7; padding: 6px; margin: 4px; border: 1px solid #8da1b4; border-radius: 5px; line-height: 60%"><p style="margin-bottom: 0px">Resource Ingredient &quot;ingredientMICROCRYSTALLINECELLULOSE&quot; </p><p style="margin-bottom: 0px">Profile: <a href="https://build.fhir.org/ig/HL7/emedicinal-product-info//StructureDefinition-Ingredient-uv-epi.html">Ingredient (ePI)</a></p></div><p><b>[identifier](http://hl7.org/fhir/R5/ingredient.html#Ingredient.identifier)</b>: id: OP1R32D61U ([use](http://hl7.org/fhir/R5/datatypes.html#Identifier#Identifier.use): OFFICIAL)</p><p><b>status</b>: active</p><p><b>for</b>: </p><ul><li><a href="#MedicinalProductDefinition_mp1mg">See above (MedicinalProductDefinition/mp1mg)</a></li><li><a href="#MedicinalProductDefinition_mp025mg">See above (MedicinalProductDefinition/mp025mg)</a></li></ul><p><b>role</b>: Excipient <span style="background: LightGoldenRodYellow; margin: 4px; border: 1px solid khaki"> (rmswi#100000072082)</span></p><h3>Manufacturers</h3><table class="grid"><tr><td style="display: none">-</td><td><b>Manufacturer</b></td></tr><tr><td style="display: none">*</td><td><a href="#Organization_org1">See above (Organization/org1)</a></td></tr></table><blockquote><p><b>substance</b></p><h3>Codes</h3><table class="grid"><tr><td style="display: none">-</td><td><b>Concept</b></td></tr><tr><td style="display: none">*</td><td>MICROCRYSTALLINE CELLULOSE <span style="background: LightGoldenRodYellow; margin: 4px; border: 1px solid khaki"> (beta#OP1R32D61U)</span></td></tr></table></blockquote></div>
        </text>
        <identifier>
          <use [value](http://hl7.org/fhir/R5/datatypes.html#code)="official"/>
          <[system](http://hl7.org/fhir/R5/datatypes.html#Identifier#Identifier.system) [value](http://hl7.org/fhir/R5/datatypes.html#uri)="https://gsrs.ncats.nih.gov/ginas/app/beta"/>
          <[value](http://hl7.org/fhir/R5/datatypes.html#Identifier#Identifier.value) [value](http://hl7.org/fhir/R5/datatypes.html#string)="OP1R32D61U"/>
        </identifier>
        <[status](http://hl7.org/fhir/R5/ingredient.html#Ingredient.status) [value](http://hl7.org/fhir/R5/datatypes.html#code)="active"/>```
