### ISSUE TITLE
Use of lists

### ISSUE THREAD

**Issue by jkiddo** [hl7-eu/gravitate-health#15]
@amedranogil / @joofio / @10alejospain / @gmej / @cander2 can we agree to the following:

We will use the List resource to group ePI's that are for the same thing (in lack of better word) that has the same identifier but where language is different. This follows the design of EMA. An example is https://github.com/hl7-eu/gravitate-health/blob/836fdcc6af3abd6b7c03affb28a153fb6203ea17/input/fsh/examples/List.fsh#L81 which is Dovato. The list contains links to (pre)processed ePI's that are ready to be consumed together with an IPS. The binding contract to the focusing service is then that you provide the IPS together with the id of the client-selected reference - as I'm already doing for the danish scenario.

Are there any comments to doing this? A consequence of this is that we need to make more example Lists in the IG as they will serve as grouping mechanism.

**Comment by cander2** [comment]
Yes, agree. 

I believe all of these documents will have the same EMA product number but is that enough for us to keep track of everything? 

With FDA's SPL, each document has an id root and a setId. All documents in the List get the same setId to retrieve the entire List of documents in the group (including their versions). id root is unique for each document and each version.

With ePI, 

1. Does List.id = setId? 
2. Does List.entry.reference (Bundle) = id root?

If yes, then how do we get the superseded versions? Would you have to find the individual document first, which leads to the current and then get its prior versions?

**Comment by cander2** [comment]
FYI - a colleague just shared this with me:

HOW IS THE EU NUMBER COMPOSED? 
EU/[1/2/3]/[YY]/[NNN]/[XXX] 

EU Indicates that it is a European centrally authorised or designated product 
[1/2/3] 1 Human, 2 Veterinary, 3 Orphan medicinal product 
[YY] last two digits of the year (98 for 1998; 04 for 2004) 
[NNN] chronological number of product authorised (NNNN from 1000 on) 
[XXX] number attributed to each individual package presentation of this product

[untitled (europa.eu)](https://ec.europa.eu/health/documents/community-register/register_faq.pdf) - source is bottom of page 6

**Comment by jkiddo** [comment]
> Yes, agree. 
> 
> I believe all of these documents will have the same EMA product number but is that enough for us to keep track of everything? 
> 
> With FDA's SPL, each document has an id root and a setId. All documents in the List get the same setId to retrieve the entire List of documents in the group (including their versions). id root is unique for each document and each version.
> 
> With ePI, 
> 
> 1. Does List.id = setId? 
> 2. Does List.entry.reference (Bundle) = id root?
> 
> If yes, then how do we get the superseded versions? Would you have to find the individual document first, which leads to the current and then get its prior versions?

I think setId would be List.identifier and id.root would be the identifier (not id) on the particular referenced Bundle. Identifiers are intended to carry that kind of meaning - not Id's.

In terms of history there are two approaches here: Either retain historical entries but mark them as deleted (or we make an extension for 'deprecated' content) - or - the document bundles are simply updated and we use the regular _history part of the specification. If need be, we can also have history references in the list as default. To sum up: we have options to cover it.

**Comment by jkiddo** [comment]
@cander2 see also https://www.hl7.org/fhir/http.html#history

**Comment by jkiddo** [comment]
@cander2 / @joofio following up on this: We need more _corrected_ samples of processed ePI Lists in https://github.com/hl7-eu/gravitate-health/blob/master/input/fsh/examples/List.fsh. Currently the only usable List is the https://github.com/hl7-eu/gravitate-health/blob/f61fad32cad0172c6d575d5bd3b35a6a8386ac4b/input/fsh/examples/List.fsh#L81 as the entries in it are the processed ones and the entries only differ in language. I need more samples of Lists that groups processed ePI's where they only differ in language. I would like to request at least two more example lists: one for Karvea and another of your own choice. Can I have that within this month?

**Comment by joofio** [comment]
yes. will tell when its ready

Jens Kristian Villadsen ***@***.***> escreveu no dia domingo,
15/10/2023 à(s) 16:18:

**Comment by joofio** [comment]
processed for which lenses?pregnancy? @jkiddo

**Comment by cander2** [comment]
Do you mean you need a lifecycle? Something like this:
Skilarence v1 English (one indication)
Skilarence v2 French (one indication)
Skilarence v2 English (two indications)
Skilarence v2 French (two indications)
Skilarence v3 French (fix a typo)

Or do you mean you need Lists for a couple products?

**Comment by jkiddo** [comment]
I need lists

**Comment by joofio** [comment]
added list of karvea preprocessed in another language as the original (portuguese :) )

**Comment by joofio** [comment]
biktarvy also added. please test to check if anything is missing

**Comment by joofio** [comment]
Lists added. Lifecycle to be addressed in other issues
