### ISSUE TITLE
use of span for focusing on text

### ISSUE THREAD

**Issue by cander2** [hl7-eu/gravitate-health#16]
Since span cannot be used across paragraphs, how would we highlight multi-paragraph text?

For instance, this indication is two paragraphs. How would be highlight both at one time?

4. CLINICAL PARTICULARS
4.1 Therapeutic indications
Karvea is indicated in adults for the treatment of essential hypertension.
It is also indicated for the treatment of renal disease in adult patients with hypertension and type 2 
diabetes mellitus as part of an antihypertensive medicinal product regimen (see sections 4.3, 4.4, 4.5 
and 5.1).

**Comment by joofio** [comment]
With div

Craig Anderson ***@***.***> escreveu em qua., 4/10/2023 às
20:38 :

**Comment by cander2** [comment]
Instead of span we use div? Like this,

```
* text.div = """<div xmlns='http://www.w3.org/1999/xhtml'> 
<div class="IndicationHypertension">   
<p> Karvea is indicated in adults for the treatment of essential hypertension.</p>
            <p>It is also indicated for the treatment of renal disease in adult patients with hypertension and type 2
diabetes mellitus as part of an antihypertensive medicinal product regimen (see sections 4.3, 4.4, 4.5
and 5.1).</p>
</div>
        </div>"""
```
