### ISSUE TITLE
Transition to R5

### ISSUE THREAD

**Issue by jvitrifork** [hl7-eu/gravitate-health#18]
@gcangioli we would like to transition to R5. How do we cope with this when IPS is R4? I've had to remove all samples from the IG in https://github.com/hl7-eu/gravitate-health/tree/feature/r5-support as they were not R5 compatible

**Comment by gcangioli** [comment]
@jvitrifork no plans to move to R5 for the IPS. 
I think we need to carefully understand the impact to move to R5 instead of R4b
how many implementations based on FHIR R5 (beside the Pharma regulatory part)  will be actually used on the next years ?
