### ISSUE TITLE
Need help solving this error

### ISSUE THREAD

**Issue by cander2** [hl7-eu/gravitate-health#20]
Any idea what the error is?
https://github.com/hl7-eu/gravitate-health/actions/runs/6607474629/job/17944907204

I tried adding anker tags with classes for breastCancer, allergen, 025mg, and 1mg in certain spots. From an XML/HTML standpoint the Visual Studio says it is compliant. Guessing there is something about this that the FHIR spec doesn't like though.

**Comment by joofio** [comment]
its a bug as far as i know. triggered by two subjects on composition

Craig Anderson ***@***.***> escreveu no dia segunda,
23/10/2023 à(s) 12:52:

**Comment by cander2** [comment]
That's odd, the profile and base Resource have 0..* on Subject.

Is it ok to just ignore it or is there a way to fix or avoid it?

**Comment by joofio** [comment]
Already corrected to avoid it


Craig Anderson ***@***.***> escreveu em seg., 23/10/2023 às
13:30 :

**Comment by cander2** [comment]
Thank you!

**Comment by gcangioli** [comment]
..mmmhh two subjects should work in R5, is this a validator bug ?

**Comment by joofio** [comment]
i would suggest that it is...
check here the changes:
https://github.com/hl7-eu/gravitate-health/commit/2377b63cf006efc1a7ef6ddf73988508454b3590
left returns the error.
Removing. returns ok

**Comment by cander2** [comment]
To do multiple subjects would it work like this for a leaflet with three medicinal products:
```
* subject
* subject[+]
* Subject[+]
```

**Comment by joofio** [comment]
In theory would be something like that


Craig Anderson ***@***.***> escreveu em seg., 23/10/2023 às
20:43 :
