### ISSUE TITLE
Anyone ever see this happen? Artifacts page all blue from XML ePI

### ISSUE THREAD

**Issue by cander2** [hl7-eu/gravitate-health#24]
I tried switching from a FSH ePI to an XML version. The XML clears validation without issue but the Artifacts page shows as all blue.

Link to the source XML:
https://github.com/hl7-eu/gravitate-health/blob/master/input/resources/Bundle-bundlepackageleaflet-talzenna1mgand025mg.xml

Link to the Artifacts page with all blue:
https://build.fhir.org/ig/hl7-eu/gravitate-health/branches/master/Bundle-bundlepackageleaflet-talzenna1and025.html

![image](https://github.com/hl7-eu/gravitate-health/assets/88413525/29303646-e59a-4e81-b0bb-069c9faa6227)

**Comment by costateixeira** [comment]
This is a template issue. The (footer?) color is setting the color and
since the previous divs are not closed, this bleeds to the content.
There's a div not being closed, possibly this one:
https://github.com/hl7-eu/gravitate-health/blob/master/ig-template/package/includes/epi.liquid#L48C4-L48C8
