### ISSUE TITLE
[XL] FHIR Lens metadata

### ISSUE THREAD

**Issue by joofio** [hl7-eu/gravitate-health#29]
@amedranogil " will we want to make the Lens metadata standard in FHIR ?"

adding @jkiddo to the topic as well

to add to the topic as well. I was thinking of using lens as library resource https://build.fhir.org/library.html

**Comment by amedranogil** [comment]
Lens Metadata should include:

- name
- intent / description of the patients this lens is intented towards
- input parameters (for GDPR enforcement)
- explanation/disclaimer
- compatible / recommended / alternative lenses
- author / owner 
- license
- documentation link
- certification (if any)
- link to the code, if not the code itself (we may have different types of code, in the future)
- version of the lense
- version of the LEE interface the lens is compatible with
- region / juridisdiction of the lens
- icon for the lens (compliant with a set of style rules)

Having the lens as a FHIR resource will be very nice, since we could apply the CTF directly managing provenance and therefore trust and integrity of the lens would also be handled

**Comment by jkiddo** [comment]
First thought that comes to mind is to do it as a Basic resource with a range of extensions

**Comment by jkiddo** [comment]
Profile and example instance should go into the gravitate IG

**Comment by joofio** [comment]
@amedranogil whats "version of the LEE interface the lens is compatible with" ? 
I am building a logical model based on your requirements and we can go from there

**Comment by joofio** [comment]
tentative idea for logical model (https://build.fhir.org/ig/hl7-eu/gravitate-health/branches/master/StructureDefinition-Lens.html)

The example i had envisioned before: 
* https://build.fhir.org/ig/hl7-eu/gravitate-health/branches/master/StructureDefinition-Lenses.html 
* https://github.com/hl7-eu/gravitate-health/blob/e1179cf2e77871daed9e3e4c086ff8f48c757bb4/input/fsh/examples/focusedEPI/e_karvea.fsh#L1C3-L1C3

**Comment by joofio** [comment]
meeting 5/12: understand if the code is in the lens or not.

**Comment by amedranogil** [comment]
> @amedranogil whats "version of the LEE interface the lens is compatible with" ? I am building a logical model based on your requirements and we can go from there

The lenses should comply with a specific interface, both for FOSPS to execute them, as well as the Lens to call certain utility functions to make the lens code much more readable. This interface is called de Lens Execution Environment (LEE), and could evolve in the future.

Thus it is always good practice to refer which version of the LEE the lens is compatible with, as this could determine the compatibility of said lens.

Of course this only applies to JavaScript Lenses, if we have more codification scripts, then the parameter should refer to the interpreter and the interface for it (I think this would be the abstract interpretation of LEE).

**Comment by joofio** [comment]
my idea of lens here:
i think i could fit all of the needed data in here:
@jkiddo i still believe this is better than basic, what do you think?
https://build.fhir.org/ig/hl7-eu/gravitate-health/StructureDefinition-lens.html

**Comment by jkiddo** [comment]
@joofio Yeah - you're right on that. So you're thinking a library pr lens?

**Comment by joofio** [comment]
yes. you see any issue with that? I didnt see any issue with that.

however, if we could group lenses under a certain category, we could add an extension to categorise them. (in the attachment element for example). I dont see the need for that atm.

**Comment by jkiddo** [comment]
Sounds good to me

**Comment by jkiddo** [comment]
Will there be a one-2-one mapping between the highlights/modifications and the lens? Or can a lens exist as a composition of lenses or can a lens do multiple highlights/modifications?

**Comment by jkiddo** [comment]
-also: if lenses should be in control from end user we need:
1) to expose the supported lenses (in the https://build.fhir.org/ig/hl7-eu/gravitate-health/CapabilityStatement-capabilityStatement.html)
2) make them optional parameters as either id or identifiers in https://build.fhir.org/ig/hl7-eu/gravitate-health/OperationDefinition-focus.html

**Comment by amedranogil** [comment]
> Will there be a one-2-one mapping between the highlights/modifications and the lens? 

not necessarily, the lens is open to do anything. We have decided to take to the PEG this question, for better interpretation of the capabilities of the lenses, have more understandable names...

From this discussion I was inspired to proposed a declarative aspect of the lens (either CapabilityStatement, or another specification) which could be used to pre-select lenses given an IPS(+PV). So the lens would state "I am useful for pregnant patients" (giving in declarative form the conditions of the lens) and it would be pre-selected for those conditions.

> Or can a lens exist as a composition of lenses or can a lens do multiple highlights/modifications?

Yes, more or less, logically there can be a "tree" of lenses where branches would compose diferent lenses into "one". I am not sure if at this stage we need to standardise the concept of "composition of lenses".

**Comment by amedranogil** [comment]
Dumb Question: The StructureDefinition-lens can be signed right? This could be interesting for the CTF

**Comment by joofio** [comment]
yes it can

**Comment by joofio** [comment]
meet 9.2.24

- add topic,
- extension for LEE. (or versionAlgorithm)
- valueset for topic
- subject?
-

**Comment by joofio** [comment]
updated to reflect last conversation
https://build.fhir.org/ig/hl7-eu/gravitate-health/StructureDefinition-lens.html

**Comment by joofio** [comment]
example of a searchset for returning lenses. this should be the spec of the <URL>/focusing/lenses

Ideally in FHIR we could change the URL to <URL>/fhir/Library and then
if we added the ID of each Lenses like <URL>/fhir/Library/<ID> would return the single resource.

EDIT: Link: https://build.fhir.org/ig/hl7-eu/gravitate-health/branches/master/Bundle-BundleOfLenses.html

**Comment by aalonsolopez** [comment]
Can we close this?

**Comment by joofio** [comment]
yes but we will need imrpovements. (i.e translations)
