### ISSUE TITLE
Profile: Organization

### ISSUE THREAD

**Issue by cander2** [hl7-eu/gravitate-health#30]
identifier, should we have one slice for each region: US, EU, JP? Or make it generic for all?

Can we add alias?

Can we add a sliced telecom with one slice each for phone, email and url?

**Comment by gcangioli** [comment]
> Can we add alias?
> 
> Can we add a sliced telecom with one slice each for phone, email and url?

done (see commit above)

**Comment by cander2** [comment]
Oh yes, I like the idea of removing the slices and going with the value set approach. Probably much easier to manage all the different terminologies and probably make easier to encourage harmonization amongst the regulators.
