### ISSUE TITLE
Profile: Regulated Authorization

### ISSUE THREAD

**Issue by cander2** [hl7-eu/gravitate-health#31]
Identifier, same as organization comment, should we make this generic? Otherwise we would need one slice per country.

Can we add:
1. description
2. regulator

**Comment by gcangioli** [comment]
> Can we add:
> 
> 1. description
> 2. regulator

done

**Comment by cander2** [comment]
Yes, let’s go with this approach of a system bound to a value set. Can we adjust type to be the same?
