### ISSUE TITLE
[RMM] Specify RMM data in FHIR

### ISSUE THREAD

**Issue by joofio** [hl7-eu/gravitate-health#31]
Should it be in FHIR.
If so, how?

**Comment by joofio** [comment]
since RMM is of very different natures and to enable the data to be added directly i would say https://www.hl7.org/fhir/documentreference.html would be a good option.

calling @jkiddo @gcangioli what do you think?

i am gathering example right now

**Comment by jkiddo** [comment]
What is RMM?

**Comment by joofio** [comment]
Risk Minimization material (edited title). The idea is basicually every aditional document/data to add to epis

**Comment by joofio** [comment]
my idea of profile for this:
https://build.fhir.org/ig/hl7-eu/gravitate-health/StructureDefinition-ASM.html
will provide examples as soon as i have them

EDIT: changed link

**Comment by joofio** [comment]
examples here:
https://github.com/hl7-eu/gravitate-health/blob/master/input/fsh/examples/supportmaterial.fsh

**Comment by joofio** [comment]
I think we should also check what a focused epi would look like with the RMM?

**Comment by amedranogil** [comment]
Supporting Resources manager was implemented for FOSPS v1 (although not completed, and never used), in that version the metadata model was defined starting from standard Dulce core metadata terms (metadata for online documents), adding G-lens specific terms have been added.
SR is represented by it metadata namely:
•	Source (this can be hosted in FOSPS, or public repositories)
•	format type (document, video, image, audio, interactive, …)
•	RMM type (Routine, additional, support, …)
•	Author 
•	Provenance (CTF)
•	required Literacy level (Digital / Health)
•	Language
•	Associated standard terms (addressed disease, addressed risk, side effect management, delivery method, etc…)

**Comment by joofio** [comment]
i will change it accordingly

**Comment by amedranogil** [comment]
We have analysed DocumentRefence needed extensions and we have concluded we need to discuss these:

- Title	The display name of the material
- RMM type	Routine, additional, support, … as defined in WP7
- Author	How originally developed the material
- Required Literacy level	Digital / Health needed to correctly understand the material
- Language	Code system representing the main language, if any, needed to understand the material.
- Associated standard terms	addressed disease, addressed risk, side effect management, delivery method, etc… using standard code systems to list them. The nearest parameter in FHIR specification is category; but it may be used for other purposes.
- Modality	the particular way in which the material exists, or is experienced, i.e. visual, audio-visual, audio, …
- Type 	includes the LOINC terminology for the type of document. Includes image, video, audio, and many types of medical documentation. Generic use documents like those envisioned in G-Lens may not be covered by this terminology. not necesarily the same as Modality.
- Category 	includes the LOINC terminology values for the type of document. this should be used to add categories for searching, not sure if these categories are the associated terms.
- Content: 	In FHIR this property can be used to attach In-line representation of the document, or a reference to source through an URI. The reference should be preferred as attachments could be difficult to publish directly from the FHIR server.

**Comment by joofio** [comment]
ok we can discuss that... a meeting or through here?

**Comment by joofio** [comment]
changed to accomodate our conversation:
https://build.fhir.org/ig/hl7-eu/gravitate-health/StructureDefinition-ASM.html

@amedranogil check the documentation you made and this one. They should be in accordance. 
I can add more details / narrative to each element to explain its intent

**Comment by amedranogil** [comment]
Yes, it seems ok.
I am only missing the health / digital literacy level required to access the SM, I know we discussed these where not quantifiable yet. So this is just a reminder about this topic.
