### ISSUE TITLE
Profile: Administrable Product Definition

### ISSUE THREAD

**Issue by cander2** [hl7-eu/gravitate-health#34]
Identifier, I think we should only have one identifier here for the PhPID

Can we add:
1. property to capture characteristics with six slices. One slice each for: 
    - Colour = codeableconcept
    - flavour = codeableconcept
    - score = codeableconcept
    - shape = codeableconcept
    - size = quantity (value + units; e.g., 5 mm)
    - imprint = string

**Comment by gcangioli** [comment]
> Can we add:
> 
> 1. property to capture characteristics with six slices. One slice each for:
>    
>    * Colour = codeableconcept
>    * flavour = codeableconcept
>    * score = codeableconcept
>    * shape = codeableconcept
>    * size = quantity (value + units; e.g., 5 mm)
>    * imprint = string

which coded concepts should be used for representing these proprieties ?

**Comment by cander2** [comment]
> > Identifier, I think we should only have one identifier here for the PhPID
> 
> are you asking for having only the PhPid slice ?

Oh no, meant that cardinality is 0..1.

**Comment by cander2** [comment]
> * which coded concepts should be used for representing these proprieties ?

do you mean like this?

Colour = codeableconcept = bound to a value set 
flavour = codeableconcept = bound to a value set 
score = codeableconcept = bound to a value set 
shape = codeableconcept = bound to a value set 
size = quantity (value + units; e.g., 5 mm) = string
imprint = string

**Comment by gcangioli** [comment]
> > > Identifier, I think we should only have one identifier here for the PhPID
> > 
> > 
> > are you asking for having only the PhPid slice ?
> 
> Oh no, meant that cardinality is 0..1.

Slices have been removed. N/A
