### ISSUE TITLE
Profile: Manufactured Item Definition

### ISSUE THREAD

**Issue by cander2** [hl7-eu/gravitate-health#35]
Can we add property to capture characteristics with six slices. One slice each for:
1. Colour = codeableconcept
2. flavour = codeableconcept
3. score = codeableconcept
4. shape = codeableconcept
5. size = quantity (value + units; e.g., 5 mm)
6. imprint = string

**Comment by gcangioli** [comment]
Where possible I used http://terminology.hl7.org/CodeSystem/medicationknowledge-characteristic
I used SCT for color
not clear what to use for flavor

**Comment by gcangioli** [comment]
remaining open items in https://github.com/hl7-eu/gravitate-health/issues/42
