### ISSUE TITLE
Profile: Bundle - entry optionality

### ISSUE THREAD

**Issue by gcangioli** [hl7-eu/gravitate-health#38]
(1) are these entries all what we need in the bundle ?
(2) are cardinalities correct ?

- entry:composition		1..1	CompositionUvEpi	Electronic Product Information composition
- .... entry:organization		1..*	OrganizationUvEpi	A grouping of people or organizations with a common purpose
- .... entry:authorization		1..*	RegulatedAuthorizationUvEpi	Regulatory approval, clearance or licencing related to a regulated product, treatment, facility or activity e.g. Market Authorization for a Medicinal Product
- .... entry:medicinalProduct		1..*	MedicinalProductDefinitionUvEpi	Detailed definition of a medicinal product
- .... entry:packagedProduct		0..*	PackagedProductDefinitionUvEpi	A medically related item or items, in a container or package
- .... entry:administrableProduct		0..*	AdministrableProductDefinitionUvEpi	A medicinal product in the final form, suitable for administration - after any mixing of multiple components
- .... entry:manItem		0..*	ManufacturedItemDefinitionUvEpi	The definition and characteristics of a medicinal manufactured item, such as a tablet or capsule, as contained in a packaged medicinal product
- .... entry:ingredient		0..*	IngredientUvEpi	An ingredient of a manufactured item or pharmaceutical product
- .... entry:clinicalUse		0..*	ClinicalUseDefinitionContraindicationUvEpi, ClinicalUseDefinitionIndicationUvEpi, ClinicalUseDefinitionInteractionUvEpi, ClinicalUseDefinitionUndesirableEffectUvEpi, ClinicalUseDefinitionWarningUvEpi	A single issue - either an indication, contraindication, interaction or an undesirable effect for a medicinal product, medication, device or procedure
- .... entry:binary		0..*	Binary

**Comment by cander2** [comment]
yes, this is the correct list of resources.

Regarding cardinality,
Administrable product 1..*
Manufactured item 1..*
Ingredient 1..*

The above three should have resource cardinality of 1..1 right?

**Comment by gcangioli** [comment]
> The above three should have resource cardinality of 1..1 right?

not sure I understood what do you mean here.. I don't think there is only one ingredient or manufactured item... :-)

**Comment by cander2** [comment]
The entry for composition has this card:
- entry:composition 1..1
--resource 1..1 CompositionUvEpi

but the entry for administrable product has this card
- entry:administrableproduct 0..*
-- resource 0..1 AdministrableProductDefinitionUvEpi


It's the second line of administrable product that i'm not understanding. I interpret this as you can have none or many administrable product entries and you can have none or one administrable product resource within that entry.

But why would I have an empty entry with no resource? 

So trying to say, maybe it should look like this instead?
- entry:administrableproduct 1..*
-- resource 1..1 AdministrableProductDefinitionUvEpi

**Comment by gcangioli** [comment]
..got it..:-) ... you are right resource is 1.. even when the entry is 0..
