### ISSUE TITLE
[DOC] Create workflow for getting lens and focusing

### ISSUE THREAD

**Issue by joofio** [hl7-eu/gravitate-health#42]

**Comment by joofio** [comment]
added here
https://build.fhir.org/ig/hl7-eu/gravitate-health/14-workflow.html

@amedranogil @riccardo-leoni-dw what do you think? feedback is welcome.

**Comment by jkiddo** [comment]
Just to do a bit more deep dive (where use case 4 is the Danish one):

![image](https://github.com/hl7-eu/gravitate-health/assets/211696/407ee003-a062-4ac2-9419-dabccc4b9272)

**Comment by joofio** [comment]
great, can i add that to the IG?

**Comment by joofio** [comment]
https://build.fhir.org/ig/hl7-eu/gravitate-health/14-workflow.html
and 
https://build.fhir.org/ig/hl7-eu/gravitate-health/15-focusing-considerations.html
