### ISSUE TITLE
uuml character needs encoding

### ISSUE THREAD

**Issue by jkiddo** [hl7-eu/gravitate-health#7]
As seen on https://github.com/HL7/emedicinal-product-info/issues/82 - there are some illegal characters that needs to be encoded as numeric or hexadecimal in https://github.com/hl7-eu/gravitate-health/blob/master/input/fsh/examples/enhancedEPI/Alicia_e_calcium.fsh#L289

**Comment by joofio** [comment]
This issue was solved by substitution. However, the fact that we can include HTML in the div sections can induce in error since not every kind of html "code" is suitable to be FHIR compliant or be correctly rendered.
